set nocompatible " be iMproved, required
set encoding=utf-8 " set encoding
set exrc " read project specific vimrc files
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
" Utilities
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'trusktr/seti.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'ryanoasis/vim-devicons'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'heavenshell/vim-jsdoc'
Plugin 'Valloric/YouCompleteMe'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-sensible'
Plugin 'rking/ag.vim'
Plugin 'taiansu/nerdtree-ag'

" JavaScript
Plugin 'helino/vim-json'
Plugin 'pangloss/vim-javascript'
Plugin 'marijnh/tern_for_vim'

" Bundles
Bundle 'jistr/vim-nerdtree-tabs'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" end vim if last open window is a nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" start nerdtree tabs per default
" let g:nerdtree_tabs_open_on_console_startup=1
autocmd VimEnter * if &filetype !=# 'gitcommit' | NERDTree | endif

" enable backspace deleting
set backspace=2

" enable syntax highlighting per default
syntax on

" enable line numbers
set number

" display whitespace
autocmd BufWinEnter * if &filetype == 'nerdtree' | setlocal nolist | else | setlocal list | endif
autocmd VimEnter * if &filetype !=# 'gitcommit' | set lcs+=tab:▸\ ,eol:¬,space:.,nbsp:.  | endif
set tabstop=2
set fillchars+=vert:\

" enable icons
set guifont=Knack\ Regular\ Nerd\ Font\ 12
set laststatus=2
let g:airline_powerline_fonts = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1

" configure syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_css_checkers = ['stylelint']
let g:syntastic_typescript_checkers = ['tsc']
let g:syntastic_vim_checkers = ['vimlint']

let g:syntastic_warning_symbol = "⚠"
let g:syntastic_error_symbol = "✗"
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1

" execute syntastic commands on save
autocmd BufWritePost * SyntasticCheck
autocmd BufEnter * SyntasticCheck
autocmd InsertLeave * SyntasticCheck

" theming
hi CursorLine cterm=none ctermbg=DarkGrey
hi LineNr ctermfg=DarkGrey
hi CursorLineNr term=bold ctermfg=Yellow
hi NonText ctermfg=DarkGrey
hi SpecialKey ctermfg=DarkGrey
hi StatusLine ctermbg=DarkGrey ctermfg=DarkGrey
hi VertSplit ctermbg=DarkGrey ctermfg=DarkGrey
hi NERDTreeOpenable cterm=none ctermfg=Blue
hi NERDTreeClosable cterm=none ctermfg=Blue
hi SyntasticWarning ctermfg=Black
hi SyntasticStyleError ctermfg=Black
hi SyntasticStyleWarning ctermfg=Black
hi Search cterm=standout ctermbg=White ctermfg=DarkGrey
hi MatchParen ctermbg=DarkGrey
hi PMenu ctermbg=DarkGrey ctermfg=LightGrey
let g:airline_theme='powerlineish'

" appease vim-airline
set t_Co=16

" mappings
map <C-f> :NERDTreeFocusToggle
map <C-t> :NERDTreeTabsToggle
