source ~/.antigenrc

# appease neovim
export TERM=xterm-256color

# enable aliases to be sudo’ed
alias sudo='sudo '

# quicker navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias f="finder"
alias o="open ./"

# hidden files management
alias see='defaults write com.apple.finder AppleShowAllFiles YES;
killall Finder /System/Library/CoreServices/Finder.app'
alias unsee='defaults write com.apple.finder AppleShowAllFiles NO;
killall Finder /System/Library/CoreServices/Finder.app'
alias show='chflags nohidden'
alias hide='chflags hidden'

# convenience shortcuts
alias a='atom'
alias fuck='$(thefuck $(fc -ln -1))'
alias learn='source ~/.zshrc'
alias sd='cd /Volumes/mac-sd'
alias hd='cd /Volumes/mac-hd'
alias vundle='vim +PluginInstall +qall'

# nvm integration
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# rvm integration
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# jenv integration
PATH=$PATH:$HOME/.jenv/bin
export JENV_ROOT=/usr/local/var/jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# add node_modules/.bin/ to path
PATH=$PATH:./node_modules/.bin/

# z integration
source ~/.z.sh

# java, sigh
export JAVA_HOME=$(/usr/libexec/java_home)
